/*
 * apropos.java
 *
 * Created on 26 septembre 2002, 20:39
 */

package forms;


/**
 *
 * @author  Labayle Alexandre
 * Cette classe permet d'avoir une boite à propos qui ressemble
 * aux boites uniformisées dans de nombreuses application java
 * Elle est autonome.
 */
public final class Apropos extends javax.swing.JDialog {
    
    static java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    private String productBuildSerial;
    
    /** Creates new form apropos */
    public Apropos(java.awt.Frame parent, boolean modal, String productBuildSerial) {
        super(parent, modal);
        this.productBuildSerial = productBuildSerial;
        initComponents();
        this.setLocation((screenSize.width-(this.getSize().width))/2,(screenSize.height-(this.getSize().height))/2);
        remplirDetails();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        prodID = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        osName = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        osVersion = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        javaName = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        VMVersion = new javax.swing.JTextField();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        vendorID = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        javaHome = new javax.swing.JTextField();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        localeOS = new javax.swing.JTextField();
        jPanel51 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        userHome = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        licencePane = new javax.swing.JPanel();
        licenceScrollPane = new javax.swing.JScrollPane();
        licenceArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A propos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/splashscreen.png")));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Copyright (C) 2005  Develog");
        jPanel1.add(jLabel2, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("A propos", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jPanel8.setBorder(new javax.swing.border.TitledBorder(null, "Informations syst\u00e9me", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 255)));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gnu/icones/48x48/apps/java.png")));
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel12.add(jLabel3, java.awt.BorderLayout.WEST);

        jPanel8.add(jPanel12);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Version du produit:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel21.add(jLabel7);

        jPanel17.add(jPanel21, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel17);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Syst\u00e9me d'exploitation:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel22.add(jLabel8);

        jPanel18.add(jPanel22, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel18);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Version OS:");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel23.add(jLabel9);

        jPanel19.add(jPanel23, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel19);

        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Java:");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel24.add(jLabel10);

        jPanel20.add(jPanel24, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel20);

        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Machine Virtuelle:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel27.add(jLabel11);

        jPanel25.add(jPanel27, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel25);

        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Producteur:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel31.add(jLabel12);

        jPanel29.add(jPanel31, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel29);

        jPanel36.setLayout(new java.awt.BorderLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Java HOME:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel37.add(jLabel13);

        jPanel36.add(jPanel37, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel36);

        jPanel38.setLayout(new java.awt.BorderLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Locale du syst\u00e8me:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel39.add(jLabel14);

        jPanel38.add(jPanel39, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel38);

        jPanel40.setLayout(new java.awt.BorderLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("R\u00e9pertoire utilisateur:");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel41.add(jLabel15);

        jPanel40.add(jPanel41, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel40);

        jPanel10.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new java.awt.BorderLayout());

        prodID.setColumns(20);
        prodID.setEditable(false);
        prodID.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel16.add(prodID);

        jPanel5.add(jPanel16, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        osName.setColumns(20);
        osName.setEditable(false);
        osName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel15.add(osName);

        jPanel6.add(jPanel15, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel6);

        jPanel9.setLayout(new java.awt.BorderLayout());

        osVersion.setColumns(20);
        osVersion.setEditable(false);
        osVersion.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel14.add(osVersion);

        jPanel9.add(jPanel14, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel9);

        jPanel11.setLayout(new java.awt.BorderLayout());

        javaName.setColumns(20);
        javaName.setEditable(false);
        javaName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel32.add(javaName);

        jPanel11.add(jPanel32, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel11);

        jPanel13.setLayout(new java.awt.BorderLayout());

        VMVersion.setColumns(20);
        VMVersion.setEditable(false);
        VMVersion.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel33.add(VMVersion);

        jPanel13.add(jPanel33, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel13);

        jPanel34.setLayout(new java.awt.BorderLayout());

        vendorID.setColumns(20);
        vendorID.setEditable(false);
        vendorID.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel35.add(vendorID);

        jPanel34.add(jPanel35, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel34);

        jPanel7.setLayout(new java.awt.BorderLayout());

        javaHome.setColumns(20);
        javaHome.setEditable(false);
        javaHome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel48.add(javaHome);

        jPanel7.add(jPanel48, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel7);

        jPanel49.setLayout(new java.awt.BorderLayout());

        localeOS.setColumns(20);
        localeOS.setEditable(false);
        localeOS.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel50.add(localeOS);

        jPanel49.add(jPanel50, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel49);

        jPanel51.setLayout(new java.awt.BorderLayout());

        userHome.setColumns(20);
        userHome.setEditable(false);
        userHome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel52.add(userHome);

        jPanel51.add(jPanel52, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel51);

        jPanel10.add(jPanel4);

        jPanel8.add(jPanel10);

        jPanel26.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel28, java.awt.BorderLayout.NORTH);

        jPanel2.add(jPanel30, java.awt.BorderLayout.WEST);

        jPanel2.add(jPanel42, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel43, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("D\u00e9tails", jPanel2);

        licencePane.setLayout(new java.awt.BorderLayout());

        licenceArea.setEditable(false);
        licenceArea.setLineWrap(true);
        licenceArea.setText("Copyright (C) 2004-2004  Develog\n\nThis program is free software; you can redistribute it and/or\nmodify it under the terms of the GNU General Public License\nas published by the Free Software Foundation; either version\n2 of the License, or (at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied\nwarranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR\nPURPOSE.  See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public\nLicense along with this program; if not, write to the\nFree Software Foundation, Inc., \n59 Temple Place, Suite 330,\nBoston, MA  02111-1307  USA\n");
        licenceArea.setWrapStyleWord(true);
        licenceScrollPane.setViewportView(licenceArea);

        licencePane.add(licenceScrollPane, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Licence", licencePane);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
private void remplirDetails(){
      
    prodID.setText(productBuildSerial);
    osName.setText(System.getProperty("os.name"));
    osVersion.setText(System.getProperty("os.version"));
    javaName.setText(System.getProperty("java.runtime.name"));
    VMVersion.setText(System.getProperty("java.vm.version"));
    vendorID.setText(System.getProperty("java.vendor"));
    javaHome.setText(System.getProperty("java.home"));
    localeOS.setText(System.getProperty("user.language"));
    userHome.setText(System.getProperty("user.dir"));
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VMVersion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField javaHome;
    private javax.swing.JTextField javaName;
    private javax.swing.JTextArea licenceArea;
    private javax.swing.JPanel licencePane;
    private javax.swing.JScrollPane licenceScrollPane;
    private javax.swing.JTextField localeOS;
    private javax.swing.JTextField osName;
    private javax.swing.JTextField osVersion;
    private javax.swing.JTextField prodID;
    private javax.swing.JTextField userHome;
    private javax.swing.JTextField vendorID;
    // End of variables declaration//GEN-END:variables
    
}
