/*
 * PaneRapport.java
 *
 * Created on 20 décembre 2004, 10:35
 */

package forms;

import reports.*;

import com.develog.utils.report.engine.JRException;
import com.develog.utils.report.engine.JasperPrint;
import com.develog.utils.report.engine.*;
import com.develog.utils.report.engine.data.*;
import com.develog.utils.report.view.JRViewer;
import com.develog.utils.SmartCube;

import java.awt.BorderLayout;
import java.io.InputStream;
import java.lang.String;
import java.sql.Connection;
import java.util.HashMap;

/**
 *
 * @author  yann
 */
public class PaneRapport extends javax.swing.JPanel {
    private JRViewer viewer = null;
    /** Creates new form PaneRapport */
    public PaneRapport() {
        initComponents();
    }
    
    public PaneRapport(String nomDuRapport, HashMap param, Connection connectExt) throws Exception {
        initComponents();
        nomDuRapport = "/reports/" + nomDuRapport + ".jasper";
        JasperPrint print = null;
        InputStream fileName = this.getClass().getResourceAsStream(nomDuRapport);
        print = JasperFillManager.fillReport(fileName,param,connectExt);
        this.viewer = new JRViewer(print);
        this.add(this.viewer, BorderLayout.CENTER);
    }
    
    
    /* Permet de lancer un rapports avec son nom et son cube de données */
    public PaneRapport(String nomDuRapport, HashMap param, SmartCube SCInt) throws Exception {
        
        nomDuRapport = "/rapports/" + nomDuRapport + ".jasper";
        JRResultSetDataSource JRRInt = new JRResultSetDataSource(SCInt.getResultSetFromCube());
        JasperPrint print = null;
        InputStream fileName = this.getClass().getResourceAsStream(nomDuRapport);
        print = JasperFillManager.fillReport(fileName,param,JRRInt);
        this.viewer = new JRViewer(print);
        this.add(this.viewer, BorderLayout.CENTER);
    }	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
