/*
 * PaneMain.java
 *
 * Created on 17 décembre 2004, 15:55
 */

package forms;


import java.sql.Connection;

import javax.swing.JOptionPane;

import com.develog.database.Parametre;

/**
 *
 * @author  nahuel
 */
public class PaneMain extends javax.swing.JPanel {
    
    // Objets Centre de Gestion
    private Parametre CG_RS = null;
    private Parametre CG_ADDR = null;
    private Parametre CG_CP = null;
    private Parametre CG_VILLE = null;
    private Parametre CG_TEL = null;
    private Parametre CG_FAX = null;
    private Parametre CG_MAIL = null;
    
    // Objets Responsable
    private Parametre RG_NOM = null;
    private Parametre RG_PRENOM = null;
    private Parametre RG_ADDR = null;
    private Parametre RG_CP = null;
    private Parametre RG_VILLE = null;
    private Parametre RG_TEL = null;
    private Parametre RG_FAX = null;
    private Parametre RG_MAIL = null;    
    
    private Connection connexion        = null;
    private boolean EnModif             = false;
    
    private PrincipaleGUI papa;
    
    /** Creates new form PaneMain */
    public PaneMain(Connection connex, PrincipaleGUI papa) {
        connexion = connex;
        this.papa = papa;
        
        try {
            CG_RS = new Parametre("CG_RS",connexion,true);
            CG_ADDR = new Parametre("CG_ADDR",connexion,true);
            CG_CP = new Parametre("CG_CP",connexion,true);
            CG_VILLE = new Parametre("CG_VILLE",connexion,true);
            CG_TEL = new Parametre("CG_TEL",connexion,true);
            CG_FAX = new Parametre("CG_FAX",connexion,true);
            CG_MAIL = new Parametre("CG_MAIL",connexion,true);
            
            RG_NOM = new Parametre("RG_NOM",connexion,true);
            RG_PRENOM = new Parametre("RG_PRENOM",connexion,true);
            RG_ADDR = new Parametre("RG_ADDR",connexion,true);
            RG_CP = new Parametre("RG_CP",connexion,true);
            RG_VILLE = new Parametre("RG_VILLE",connexion,true);
            RG_TEL = new Parametre("RG_TEL",connexion,true);
            RG_FAX = new Parametre("RG_FAX",connexion,true);
            RG_MAIL = new Parametre("RG_MAIL",connexion,true);
        }catch(Exception e)
        {
            System.out.println("Erreur à l'init des params: " + e );
        }
        
        
        initComponents();
        
        this.setFields();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        coordPane = new javax.swing.JPanel();
        centrePane = new javax.swing.JPanel();
        coord1Pane = new javax.swing.JPanel();
        rsPane = new javax.swing.JPanel();
        rsLabel = new javax.swing.JLabel();
        rsField = new javax.swing.JTextField();
        addrPane = new javax.swing.JPanel();
        addrLabel = new javax.swing.JLabel();
        addrScrollPane = new javax.swing.JScrollPane();
        addrField = new javax.swing.JTextArea();
        coord2Pane = new javax.swing.JPanel();
        cpLabel = new javax.swing.JLabel();
        cpField = new javax.swing.JTextField();
        villeLabel = new javax.swing.JLabel();
        villeField = new javax.swing.JTextField();
        telLabel = new javax.swing.JLabel();
        telField = new javax.swing.JTextField();
        faxLabel = new javax.swing.JLabel();
        faxField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        respPane = new javax.swing.JPanel();
        respCoord1 = new javax.swing.JPanel();
        nomprenPane = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        preLabel = new javax.swing.JLabel();
        preField = new javax.swing.JTextField();
        addrPane1 = new javax.swing.JPanel();
        addrLabel1 = new javax.swing.JLabel();
        addrScrollPane1 = new javax.swing.JScrollPane();
        addrField1 = new javax.swing.JTextArea();
        respCoord2 = new javax.swing.JPanel();
        cpLabel1 = new javax.swing.JLabel();
        cpField1 = new javax.swing.JTextField();
        villeLabel1 = new javax.swing.JLabel();
        villeField1 = new javax.swing.JTextField();
        telLabel1 = new javax.swing.JLabel();
        telField1 = new javax.swing.JTextField();
        faxLabel1 = new javax.swing.JLabel();
        faxField1 = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        emailField1 = new javax.swing.JTextField();
        actionPane = new javax.swing.JPanel();
        addUser = new javax.swing.JButton();
        delUser = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        coordPane.setLayout(new javax.swing.BoxLayout(coordPane, javax.swing.BoxLayout.X_AXIS));

        centrePane.setLayout(new java.awt.BorderLayout(0, 5));

        centrePane.setBorder(new javax.swing.border.TitledBorder("Centre de Gestion"));
        coord1Pane.setLayout(new java.awt.BorderLayout(0, 5));

        rsPane.setLayout(new java.awt.GridLayout(1, 0));

        rsLabel.setText("Raison Sociale :");
        rsPane.add(rsLabel);

        rsField.setColumns(10);
        rsPane.add(rsField);

        coord1Pane.add(rsPane, java.awt.BorderLayout.NORTH);

        addrPane.setLayout(new java.awt.GridLayout(1, 0));

        addrLabel.setText("Addresse :");
        addrLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        addrPane.add(addrLabel);

        addrField.setColumns(10);
        addrField.setRows(3);
        addrField.setBorder(null);
        addrScrollPane.setViewportView(addrField);

        addrPane.add(addrScrollPane);

        coord1Pane.add(addrPane, java.awt.BorderLayout.CENTER);

        centrePane.add(coord1Pane, java.awt.BorderLayout.CENTER);

        coord2Pane.setLayout(new java.awt.GridLayout(5, 2, 0, 5));

        cpLabel.setText("Code Postal :");
        coord2Pane.add(cpLabel);

        cpField.setColumns(5);
        coord2Pane.add(cpField);

        villeLabel.setText("Ville :");
        coord2Pane.add(villeLabel);

        villeField.setColumns(7);
        coord2Pane.add(villeField);

        telLabel.setText("T\u00e9l\u00e9phone :");
        coord2Pane.add(telLabel);

        telField.setColumns(9);
        coord2Pane.add(telField);

        faxLabel.setText("Fax :");
        coord2Pane.add(faxLabel);

        faxField.setColumns(9);
        coord2Pane.add(faxField);

        emailLabel.setText("E-mail :");
        coord2Pane.add(emailLabel);

        emailField.setColumns(10);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        coord2Pane.add(emailField);

        centrePane.add(coord2Pane, java.awt.BorderLayout.SOUTH);

        coordPane.add(centrePane);

        respPane.setLayout(new java.awt.BorderLayout(0, 5));

        respPane.setBorder(new javax.swing.border.TitledBorder("Responsable de Gestion"));
        respCoord1.setLayout(new java.awt.BorderLayout(0, 5));

        nomprenPane.setLayout(new java.awt.GridLayout(2, 2, 0, 5));

        nomLabel.setText("Nom :");
        nomprenPane.add(nomLabel);

        nomField.setColumns(10);
        nomprenPane.add(nomField);

        preLabel.setText("Pr\u00e9nom :");
        nomprenPane.add(preLabel);

        preField.setColumns(5);
        nomprenPane.add(preField);

        respCoord1.add(nomprenPane, java.awt.BorderLayout.NORTH);

        addrPane1.setLayout(new java.awt.GridLayout(1, 2, 0, 5));

        addrLabel1.setText("Addresse :");
        addrLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        addrPane1.add(addrLabel1);

        addrScrollPane1.setViewportView(addrField1);

        addrPane1.add(addrScrollPane1);

        respCoord1.add(addrPane1, java.awt.BorderLayout.CENTER);

        respPane.add(respCoord1, java.awt.BorderLayout.CENTER);

        respCoord2.setLayout(new java.awt.GridLayout(5, 2, 0, 5));

        cpLabel1.setText("Code Postal :");
        respCoord2.add(cpLabel1);

        cpField1.setColumns(5);
        respCoord2.add(cpField1);

        villeLabel1.setText("Ville :");
        respCoord2.add(villeLabel1);

        villeField1.setColumns(7);
        respCoord2.add(villeField1);

        telLabel1.setText("T\u00e9l\u00e9phone :");
        respCoord2.add(telLabel1);

        telField1.setColumns(9);
        respCoord2.add(telField1);

        faxLabel1.setText("Fax :");
        respCoord2.add(faxLabel1);

        faxField1.setColumns(9);
        respCoord2.add(faxField1);

        emailLabel1.setText("E-mail :");
        respCoord2.add(emailLabel1);

        emailField1.setColumns(10);
        respCoord2.add(emailField1);

        respPane.add(respCoord2, java.awt.BorderLayout.SOUTH);

        coordPane.add(respPane);

        add(coordPane, java.awt.BorderLayout.CENTER);

        addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/develog/icones/stock_apply.png")));
        addUser.setToolTipText("Ajouter");
        addUser.setMaximumSize(new java.awt.Dimension(50, 26));
        addUser.setMinimumSize(new java.awt.Dimension(50, 26));
        addUser.setPreferredSize(new java.awt.Dimension(50, 26));
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        actionPane.add(addUser);

        delUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/develog/icones/stock_cancel-16.png")));
        delUser.setToolTipText("Supprimer");
        delUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delUserActionPerformed(evt);
            }
        });

        actionPane.add(delUser);

        add(actionPane, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void delUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delUserActionPerformed
                 papa.principalTab.remove(this);
    }//GEN-LAST:event_delUserActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        try {
            // Set des valeurs du centre de gestion dans la BD
            CG_RS.setValeur(rsField.getText());
            CG_ADDR.setValeur(addrField.getText());
            CG_VILLE.setValeur(villeField.getText());
            CG_CP.setValeur(cpField.getText()); 
            CG_TEL.setValeur(telField.getText());
            CG_FAX.setValeur(faxField.getText());
            CG_MAIL.setValeur(emailField.getText());

            
            // Set des valeurs du responsable de gestion dans la BD
            RG_NOM.setValeur(nomField.getText());
            RG_PRENOM.setValeur(preField.getText());
            RG_ADDR.setValeur(addrField1.getText());
            RG_VILLE.setValeur(villeField1.getText());
            RG_CP.setValeur(cpField1.getText()); 
            RG_TEL.setValeur(telField1.getText());
            RG_FAX.setValeur(faxField1.getText());
            RG_MAIL.setValeur(emailField1.getText());
            JOptionPane.showMessageDialog(this,"Les informations ont bien été enregistrées","Enregistrement effectué",JOptionPane.INFORMATION_MESSAGE,null);
            papa.principalTab.remove(this);
        }catch(Exception e) {
            System.out.println(e);
        }
        // dispose();
    }//GEN-LAST:event_addUserActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPane;
    private javax.swing.JButton addUser;
    private javax.swing.JTextArea addrField;
    private javax.swing.JTextArea addrField1;
    private javax.swing.JLabel addrLabel;
    private javax.swing.JLabel addrLabel1;
    private javax.swing.JPanel addrPane;
    private javax.swing.JPanel addrPane1;
    private javax.swing.JScrollPane addrScrollPane;
    private javax.swing.JScrollPane addrScrollPane1;
    private javax.swing.JPanel centrePane;
    private javax.swing.JPanel coord1Pane;
    private javax.swing.JPanel coord2Pane;
    private javax.swing.JPanel coordPane;
    private javax.swing.JTextField cpField;
    private javax.swing.JTextField cpField1;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JLabel cpLabel1;
    private javax.swing.JButton delUser;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailField1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField faxField;
    private javax.swing.JTextField faxField1;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JLabel faxLabel1;
    private javax.swing.JTextField nomField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JPanel nomprenPane;
    private javax.swing.JTextField preField;
    private javax.swing.JLabel preLabel;
    private javax.swing.JPanel respCoord1;
    private javax.swing.JPanel respCoord2;
    private javax.swing.JPanel respPane;
    private javax.swing.JTextField rsField;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JPanel rsPane;
    private javax.swing.JTextField telField;
    private javax.swing.JTextField telField1;
    private javax.swing.JLabel telLabel;
    private javax.swing.JLabel telLabel1;
    private javax.swing.JTextField villeField;
    private javax.swing.JTextField villeField1;
    private javax.swing.JLabel villeLabel;
    private javax.swing.JLabel villeLabel1;
    // End of variables declaration//GEN-END:variables
    
    public void setFields (){
        try{
            
            // Set des champs du centre de gestion
            rsField.setText(CG_RS.getValeur());
            addrField.setText(CG_ADDR.getValeur());
            villeField.setText(CG_VILLE.getValeur());
            cpField.setText(CG_CP.getValeur()); 
            telField.setText(CG_TEL.getValeur());
            faxField.setText(CG_FAX.getValeur());
            emailField.setText(CG_MAIL.getValeur());

            
            // Set des champs du responsable de gestion
            nomField.setText(RG_NOM.getValeur());
            preField.setText(RG_PRENOM.getValeur());
            addrField1.setText(RG_ADDR.getValeur());
            villeField1.setText(RG_VILLE.getValeur());
            cpField1.setText(RG_CP.getValeur()); 
            telField1.setText(RG_TEL.getValeur());
            faxField1.setText(RG_FAX.getValeur());
            emailField1.setText(RG_MAIL.getValeur());
                
        }catch(Exception e) {
            System.out.println("[DiversParams][SetFields] Exception lors du remplissage des champs: "+e);
        }
    }    

}
