/*
 * GenFichier.java
 *
 * Created on 3 novembre 2004, 11:56
 */

/*
 * GenFichier.java
 *
 * Created on 13 février 2004, 02:08
 */

package classes;

import forms.PrincipaleGUI;
import com.develog.io.ExtensionFilter;
import com.develog.database.DB2sql;
import java.io.IOException;
import java.io.File;
import java.io.RandomAccessFile;
import java.util.Vector;
import java.sql.Connection;
import javax.swing.*;
/**
 *
 * @author  yann
 */
public class GenFichierSvg extends javax.swing.JDialog {
    static java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    /** Creates new form GenFichier */
    public GenFichierSvg(Connection connexion, PrincipaleGUI parent, boolean modal) throws Exception{
        super(parent, false);
        File fichier = null;
        initComponents();
        this.setLocation((screenSize.width-(this.getSize().width))/2,(screenSize.height-(this.getSize().height))/2);
        ExtensionFilter ef = null;
        ef = getSaveExtensionFilter();
        fichier = getChoosedFile(ef);
        if(fichier != null) {
            setVisible(true);
            try{
                RandomAccessFile raf = new RandomAccessFile(fichier,"rws");
                //On dumpe vers ce fichier
                raf.writeBytes(DB2sql.dumpDB(connexion));
                
                //On referme le fichier.
                raf.close();
            }catch(IOException IOe) {
                throw new Exception("[GenFichier]IOe lors de l'ouverture ou de l'écriture du fichier: "+IOe);
            }
            setVisible(false);            
            parent.GestInfo("Le fichier de sauvegarde a été généré avec succès!");
        }
        dispose();
    }
    
    private File getChoosedFile(ExtensionFilter ef) {
        // Ouverture d'une boite de menu
        JFileChooser fc = new JFileChooser();
        // On applique le filtre d'extension
        fc.addChoosableFileFilter(ef);
        // Récupération du fichier
        int retval = fc.showDialog(this,null);
        if (retval == JFileChooser.APPROVE_OPTION) {
            if (!fc.accept(fc.getSelectedFile())) {
                return new File(fc.getSelectedFile().getPath()+".save");
            }else
                return fc.getSelectedFile();
        }
        return null;
    }
    
    private ExtensionFilter getSaveExtensionFilter() {
        ExtensionFilter efTexte = new ExtensionFilter("Fichiers de sauvegarde Dévelog");
        efTexte.addExtension("save");
        efTexte.addExtension("SAVE");
        return efTexte;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Progress = new javax.swing.JProgressBar();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setBorder(new javax.swing.border.EtchedBorder());
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/develog/icones/Documents2.png")));
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setOpaque(false);
        jPanel4.add(jButton2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("G\u00e9n\u00e9ration du fichier de sauvegarde en cours!");
        jPanel5.add(jLabel3, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Patientez svp...");
        jPanel5.add(jLabel4, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel5);

        jPanel4.add(jPanel6);

        jPanel3.add(jPanel4);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        Progress.setMaximum(1000);
        Progress.setIndeterminate(true);
        jPanel2.add(Progress, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar Progress;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
    
}
