/*
 * ChangeStockUserFonctionDialog.java
 *
 * Created on 20 janvier 2005, 12:08
 */

package dialogs;

import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author  nahuel
 */
public class ChangeStockUserFonctionDialog extends javax.swing.JDialog {
    static java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    private Connection connex;
    private int ST_ID;
    private int UTIL_ID;
    private forms.PaneStock papaStock;
    
    /** Creates new form ChangeStockUserFonctionDialog */
    public ChangeStockUserFonctionDialog(forms.PrincipaleGUI parent, boolean modal, int ST_ID, int UTIL_ID, Connection connex, forms.PaneStock papaStock) {
        super(parent, modal);
        this.papaStock = papaStock;
        this.connex = connex;
        this.ST_ID = ST_ID;
        this.UTIL_ID = UTIL_ID;
        
        initComponents();
        this.setLocation((screenSize.width-(this.getSize().width))/2,(screenSize.height-(this.getSize().height))/2);
        this.setResizable(false);
        this.setTitle("Edition de droits");
        
        try{
            ResultSet rset = connex.prepareStatement("SELECT UTIL_NOM, UTIL_PRENOM from UTILISATEUR where UTIL_ID = " + UTIL_ID).executeQuery();
            rset.next();
            nomLabel.setText(rset.getString("UTIL_NOM"));
            prenomLabel.setText(rset.getString("UTIL_PRENOM"));
            rset = connex.prepareStatement("SELECT ST_NOM from STOCK where ST_ID = " + ST_ID).executeQuery();
            rset.next();
            stockLabel.setText(rset.getString("ST_NOM"));
            rset = connex.prepareStatement("SELECT FO_LEVEL from FONCTION where UTIL_ID = " + UTIL_ID + " AND ST_ID = " + ST_ID).executeQuery();
            rset.next();
            switch( new Integer(rset.getString("FO_LEVEL")).intValue() ){
                case 0:agentCB.setSelected(true);break;
                case 1:adminCB.setSelected(true);break;
                default :break;
            }
        }catch(Exception e){
            System.out.println("[ChangeStockUserFonctionDialog][ChangeStockUserFonctionDialog] Exception : " + e);
            e.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        userInfoPane = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        userFonctionPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        agentCB = new javax.swing.JCheckBox();
        adminCB = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        validButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        userInfoPane.setBorder(new javax.swing.border.TitledBorder("Droits de :"));
        userInfoPane.add(nomLabel);

        userInfoPane.add(prenomLabel);

        jLabel2.setText("sur le stock :");
        userInfoPane.add(jLabel2);

        userInfoPane.add(stockLabel);

        getContentPane().add(userInfoPane, java.awt.BorderLayout.CENTER);

        userFonctionPane.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        agentCB.setText("Agent de Saisie");
        agentCB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agentCB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(agentCB);

        adminCB.setText("Administrateur");
        adminCB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        adminCB.setAutoscrolls(true);
        jPanel1.add(adminCB);

        userFonctionPane.add(jPanel1, java.awt.BorderLayout.CENTER);

        validButton.setText("Valider");
        validButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validButtonActionPerformed(evt);
            }
        });

        jPanel2.add(validButton);

        userFonctionPane.add(jPanel2, java.awt.BorderLayout.EAST);

        getContentPane().add(userFonctionPane, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void validButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validButtonActionPerformed
        try{
            if( adminCB.isSelected() )
                connex.prepareStatement("UPDATE FONCTION SET FO_LEVEL = 1 WHERE ST_ID = " + ST_ID + " AND UTIL_ID = " + UTIL_ID).executeUpdate();
            else if ( agentCB.isSelected() )
                connex.prepareStatement("UPDATE FONCTION SET FO_LEVEL = 0 WHERE ST_ID = " + ST_ID + " AND UTIL_ID = " + UTIL_ID).executeUpdate();
            else
                connex.prepareStatement("DELETE FROM FONCTION WHERE ST_ID = " + ST_ID + " AND UTIL_ID = " + UTIL_ID).execute();
            
            papaStock.refreshUsers(ST_ID);
            this.dispose();
        }catch(Exception e){
            System.out.println("[ChangeStockUserFonctionDialog][validButtonActionPerformed] Exception : " + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_validButtonActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCB;
    private javax.swing.JCheckBox agentCB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JPanel userFonctionPane;
    private javax.swing.JPanel userInfoPane;
    private javax.swing.JButton validButton;
    // End of variables declaration//GEN-END:variables
    
}
