/*
 * choixCategorie.java
 *
 * Created on 12 août 2004, 12:44
 */

package dialogs;
import com.develog.utils.SmartCube;
import com.develog.utils.SmartConnector;
import java.util.Vector;
import java.util.Hashtable;
import javax.swing.JOptionPane;

/**
 *
 * @author  alexandre
 */
public class ChoixCategorie extends javax.swing.JDialog {
    
    private Vector cateGUI = new Vector();
    private SmartConnector categorieconnector;
    private SmartCube categorieSC;
    private int intCA_PID = 1;
    private String intSection ;
    private boolean intState;
    
    /** Creates new form choixCategorie */
    public ChoixCategorie(java.awt.Frame parent, boolean modal, SmartCube categorie, int CA_PID, String section, boolean state) {
        super(parent, modal);
        categorieSC = categorie;
        intSection = section;
        intCA_PID = CA_PID;
        intState  = state;
        initComponents();
        try{
           cateGUI.add(jPanel1);
           /* On attache un connecteur à l'interface entre l'entité et le cube */
           categorieconnector = new SmartConnector(categorieSC ,cateGUI);
           categorieconnector.setEditable(true);
           if (state==false) categorieconnector.setValuesFromCube();
        }catch(Exception e){System.out.println("ici:" + e);};
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        validButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel1.setText("Nom de la cat\u00e9gorie:");
        jPanel1.add(jLabel1);

        jTextField1.setColumns(15);
        jTextField1.setName("CA_NOM");
        jPanel1.add(jTextField1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        validButton.setFont(new java.awt.Font("Dialog", 0, 12));
        validButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/develog/icones/stock_ok_20.png")));
        validButton.setText("Valider");
        validButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validButtonActionPerformed(evt);
            }
        });

        jPanel3.add(validButton);

        cancelButton.setFont(new java.awt.Font("Dialog", 0, 12));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/develog/icones/stock_cancel_20.png")));
        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel3.add(cancelButton);

        jPanel2.add(jPanel3, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void validButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validButtonActionPerformed
        if (intState){
            //Ajoute une ligne
            Hashtable Info = new Hashtable();
            Info.put("CA_PARENT",new Integer(""+intCA_PID));
            Info.put("CA_VISIBLE",new Boolean(true));
            try{ 
                categorieconnector.genNewRowWithID();
                categorieSC.setCubeData(Info);       
                categorieconnector.addNewRowWithID();
                categorieSC.commitDBTransaction();
                this.dispose();
            }catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(this,"Impossible d'ajouter","Erreur d'ajout",JOptionPane.ERROR_MESSAGE,null);
            }
        }
        else {
           try{ 
                categorieconnector.updateRow();
                categorieSC.commitDBTransaction();
                this.dispose();
            }catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(this,"Impossible de renommer","Erreur",JOptionPane.ERROR_MESSAGE,null);
            }
        }
    }//GEN-LAST:event_validButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton validButton;
    // End of variables declaration//GEN-END:variables
    
}
