/*
 * login.java
 *
 * Created on 26 novembre 2004, 11:59
 */

package dialogs;
import forms.PrincipaleGUI;
import java.sql.*;

/**
 *
 * @author  alexandre
 */
public class Login extends javax.swing.JDialog {
    
    public boolean flag = false;
    public PrincipaleGUI papounet;
    private int essai = 3;
    
    /** Creates new form login */
    public Login(forms.PrincipaleGUI parent, boolean modal) {
        super(parent, modal);
        papounet = parent;
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                System.exit(0);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jp = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Validation = new javax.swing.JButton();
        Annulation = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        UtilisateurPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        utilisateur = new javax.swing.JTextField();
        PasswordPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Identification");
        jp.setLayout(new java.awt.BorderLayout());

        Validation.setFont(new java.awt.Font("Dialog", 0, 12));
        Validation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gnu/icones/22x22/actions/button_ok.png")));
        Validation.setText("ok");
        Validation.setAlignmentY(2.0F);
        Validation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Validation.setPreferredSize(new java.awt.Dimension(76, 30));
        Validation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidationActionPerformed(evt);
            }
        });

        jPanel2.add(Validation);

        Annulation.setFont(new java.awt.Font("Dialog", 0, 12));
        Annulation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gnu/icones/22x22/actions/button_cancel.png")));
        Annulation.setText("annuler");
        Annulation.setAlignmentY(2.0F);
        Annulation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Annulation.setPreferredSize(new java.awt.Dimension(103, 30));
        Annulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulationActionPerformed(evt);
            }
        });

        jPanel2.add(Annulation);

        jp.add(jPanel2, java.awt.BorderLayout.EAST);

        jp.add(jSeparator1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jp, java.awt.BorderLayout.SOUTH);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gnu/icones/48x48/apps/password.png")));
        jPanel4.add(jLabel3);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel1.setText("Utilisateur:");
        UtilisateurPanel.add(jLabel1);

        utilisateur.setColumns(10);
        UtilisateurPanel.add(utilisateur);

        jPanel5.add(UtilisateurPanel, java.awt.BorderLayout.NORTH);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setText("Password:");
        PasswordPanel.add(jLabel2);

        password.setColumns(10);
        password.setPreferredSize(new java.awt.Dimension(110, 19));
        PasswordPanel.add(password);

        jPanel5.add(PasswordPanel, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel5);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void AnnulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulationActionPerformed
  System.exit(0);
    }//GEN-LAST:event_AnnulationActionPerformed

    private void ValidationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidationActionPerformed
    /* papounet.setUserName(user());
    papounet.setPassword(passwd()); */
        
    try{
        papounet.initConnectionSQL();
        if (papounet.TestUser(utilisateur.getText(), password.getText())){
            papounet.Login(utilisateur.getText(), password.getText());
            this.dispose();
        }else
            papounet.GestErreur("Login ou mot de passe incorrect");
    }
     catch(ClassNotFoundException ErrFound){ 
        papounet.GestErreur("Driver de base de donnees abscent!\n");
        System.exit(0);
     }
      /* Echec d'autentification */
     catch(SQLException ErrSQL){ 
        
         papounet.GestErreur("Identifiant ou mot de passe incorrect\n" + ErrSQL);
         System.out.println(ErrSQL+"\n");
         ErrSQL.printStackTrace();
         
        reset();
        essai --;
        if (essai==0) {
            System.exit(0);
        }
     }
    catch(Exception e){
        papounet.GestErreur(e.toString());
        reset();
        essai --;
    }
    }//GEN-LAST:event_ValidationActionPerformed
    public String user(){
        return utilisateur.getText();
    }
    
    /* Cette methode retourne le contenu du champs PASSWORD 
     */
    public String passwd(){
        char[] tableau = password.getPassword();
        return new String(tableau);
    }
    
    /* Cette methode permet de reinitialiser l'objet */
    public void reset(){
        utilisateur.setText(null);
        password.setText(null);
        flag = false;
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulation;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JPanel UtilisateurPanel;
    private javax.swing.JButton Validation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField utilisateur;
    // End of variables declaration//GEN-END:variables
    
}
