/*
 * SelectTree.java
 *
 * Created on 10 octobre 2005, 13:04
 */

package dialogs;

import forms.PaneProduitsUser;

import javax.swing.tree.*;

import java.util.Hashtable;

/**
 *
 * @author  nahuel
 */
public class SelectTree extends javax.swing.JDialog {
    private DefaultTreeModel treeModel;
    private PaneProduitsUser parent;
    private int prod_id;
    private Hashtable inverse;
    /** Creates new form SelectTree */
    public SelectTree(java.awt.Frame parentt, forms.PaneProduitsUser parent, boolean modal, DefaultTreeModel treeModel, int prod_id, Hashtable inverse) {
        super(parentt, modal);
        this.treeModel = treeModel;
        this.parent = parent;
        this.prod_id = prod_id;
        this.inverse = inverse;
        initComponents();
        
        categoryTree.setModel(treeModel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        catListPane = new javax.swing.JScrollPane();
        categoryTree = new javax.swing.JTree();
        acceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        catListPane.setAutoscrolls(true);
        catListPane.setViewportView(categoryTree);

        getContentPane().add(catListPane, java.awt.BorderLayout.CENTER);

        acceptButton.setText("Selectionner");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        getContentPane().add(acceptButton, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        Integer selectedCAID = (Integer)inverse.get(categoryTree.getLastSelectedPathComponent());
        if(selectedCAID == null)
            selectedCAID = new Integer(0);
        parent.setProductCat(selectedCAID.intValue(),prod_id);
        
        this.dispose();
    }//GEN-LAST:event_acceptButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JScrollPane catListPane;
    private javax.swing.JTree categoryTree;
    // End of variables declaration//GEN-END:variables
    
}
