/*
 * Generated by JasperReports - 24/03/05 14:53
 */
import com.develog.utils.report.engine.*;
import com.develog.utils.report.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class commande extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_ST_ID = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_CO_ID = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;

    private JRFillField field_CO_DATE = null;
    private JRFillField field_ST_ADRESSE = null;
    private JRFillField field_ST_CP = null;
    private JRFillField field_FO_NOM = null;
    private JRFillField field_AR_ID = null;
    private JRFillField field_ST_NOM = null;
    private JRFillField field_CC_QT = null;
    private JRFillField field_ST_VILLE = null;
    private JRFillField field_AR_DESIGN = null;
    private JRFillField field_AR_PRIX = null;
    private JRFillField field_TVA_TX = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_Fournisseur_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_ST_ID = (JRFillParameter)parsm.get("ST_ID");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_CO_ID = (JRFillParameter)parsm.get("CO_ID");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");

        field_CO_DATE = (JRFillField)fldsm.get("CO_DATE");
        field_ST_ADRESSE = (JRFillField)fldsm.get("ST_ADRESSE");
        field_ST_CP = (JRFillField)fldsm.get("ST_CP");
        field_FO_NOM = (JRFillField)fldsm.get("FO_NOM");
        field_AR_ID = (JRFillField)fldsm.get("AR_ID");
        field_ST_NOM = (JRFillField)fldsm.get("ST_NOM");
        field_CC_QT = (JRFillField)fldsm.get("CC_QT");
        field_ST_VILLE = (JRFillField)fldsm.get("ST_VILLE");
        field_AR_DESIGN = (JRFillField)fldsm.get("AR_DESIGN");
        field_AR_PRIX = (JRFillField)fldsm.get("AR_PRIX");
        field_TVA_TX = (JRFillField)fldsm.get("TVA_TX");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_Fournisseur_COUNT = (JRFillVariable)varsm.get("Fournisseur_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1149 : // parameterDefaultValue_CO_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1143 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1162 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getValue()));
                break;
            }
            case 1158 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1160 : // textField_4
            {
                value = (java.lang.String)("BON DE COMMANDE N°" + ((java.lang.Integer)parameter_CO_ID.getValue()));
                break;
            }
            case 1144 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1159 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 1163 : // textField_7
            {
                value = (java.lang.String)((((((java.math.BigDecimal)field_TVA_TX.getValue()).divide(new BigDecimal(100),4,java.math.BigDecimal.ROUND_HALF_EVEN)).add(new BigDecimal(1))).multiply(((java.math.BigDecimal)field_AR_PRIX.getValue()))).divide(new BigDecimal(1),2,java.math.BigDecimal.ROUND_HALF_EVEN) +" ¤");
                break;
            }
            case 1141 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1146 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1152 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_FO_NOM.getValue()));
                break;
            }
            case 1153 : // textField_2
            {
                value = (java.lang.String)("A " + ((java.lang.String)field_ST_VILLE.getValue()) + ", le " +  ((java.util.Date)field_CO_DATE.getValue()).toString().substring(8,10) + "/" + ((java.util.Date)field_CO_DATE.getValue()).toString().substring(5,7) + "/" + ((java.util.Date)field_CO_DATE.getValue()).toString().substring(0,4));
                break;
            }
            case 1154 : // textField_3
            {
                value = (java.lang.String)("Adresse de livraison : " + ((java.lang.String)field_ST_NOM.getValue()) + " - " + ((java.lang.String)field_ST_ADRESSE.getValue()) + " - " + ((java.lang.String)field_ST_CP.getValue()) + " " + ((java.lang.String)field_ST_VILLE.getValue()));
                break;
            }
            case 1151 : // group_Fournisseur
            {
                value = (java.lang.Object)(((java.lang.String)field_FO_NOM.getValue()));
                break;
            }
            case 1155 : // variable_Fournisseur_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1161 : // textField_5
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CC_QT.getValue()).divide(new BigDecimal(1),2,java.math.BigDecimal.ROUND_HALF_EVEN));
                break;
            }
            case 1148 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1145 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1142 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1156 : // variableInitialValue_Fournisseur_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1150 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1147 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1157 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1149 : // parameterDefaultValue_CO_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1143 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1162 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getOldValue()));
                break;
            }
            case 1158 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1160 : // textField_4
            {
                value = (java.lang.String)("BON DE COMMANDE N°" + ((java.lang.Integer)parameter_CO_ID.getValue()));
                break;
            }
            case 1144 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1159 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 1163 : // textField_7
            {
                value = (java.lang.String)((((((java.math.BigDecimal)field_TVA_TX.getOldValue()).divide(new BigDecimal(100),4,java.math.BigDecimal.ROUND_HALF_EVEN)).add(new BigDecimal(1))).multiply(((java.math.BigDecimal)field_AR_PRIX.getOldValue()))).divide(new BigDecimal(1),2,java.math.BigDecimal.ROUND_HALF_EVEN) +" ¤");
                break;
            }
            case 1141 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1146 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1152 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_FO_NOM.getOldValue()));
                break;
            }
            case 1153 : // textField_2
            {
                value = (java.lang.String)("A " + ((java.lang.String)field_ST_VILLE.getOldValue()) + ", le " +  ((java.util.Date)field_CO_DATE.getOldValue()).toString().substring(8,10) + "/" + ((java.util.Date)field_CO_DATE.getOldValue()).toString().substring(5,7) + "/" + ((java.util.Date)field_CO_DATE.getOldValue()).toString().substring(0,4));
                break;
            }
            case 1154 : // textField_3
            {
                value = (java.lang.String)("Adresse de livraison : " + ((java.lang.String)field_ST_NOM.getOldValue()) + " - " + ((java.lang.String)field_ST_ADRESSE.getOldValue()) + " - " + ((java.lang.String)field_ST_CP.getOldValue()) + " " + ((java.lang.String)field_ST_VILLE.getOldValue()));
                break;
            }
            case 1151 : // group_Fournisseur
            {
                value = (java.lang.Object)(((java.lang.String)field_FO_NOM.getOldValue()));
                break;
            }
            case 1155 : // variable_Fournisseur_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1161 : // textField_5
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CC_QT.getOldValue()).divide(new BigDecimal(1),2,java.math.BigDecimal.ROUND_HALF_EVEN));
                break;
            }
            case 1148 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1145 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1142 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1156 : // variableInitialValue_Fournisseur_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1150 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1147 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1157 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1149 : // parameterDefaultValue_CO_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1143 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1162 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getValue()));
                break;
            }
            case 1158 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1160 : // textField_4
            {
                value = (java.lang.String)("BON DE COMMANDE N°" + ((java.lang.Integer)parameter_CO_ID.getValue()));
                break;
            }
            case 1144 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1159 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 1163 : // textField_7
            {
                value = (java.lang.String)((((((java.math.BigDecimal)field_TVA_TX.getValue()).divide(new BigDecimal(100),4,java.math.BigDecimal.ROUND_HALF_EVEN)).add(new BigDecimal(1))).multiply(((java.math.BigDecimal)field_AR_PRIX.getValue()))).divide(new BigDecimal(1),2,java.math.BigDecimal.ROUND_HALF_EVEN) +" ¤");
                break;
            }
            case 1141 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1146 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1152 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_FO_NOM.getValue()));
                break;
            }
            case 1153 : // textField_2
            {
                value = (java.lang.String)("A " + ((java.lang.String)field_ST_VILLE.getValue()) + ", le " +  ((java.util.Date)field_CO_DATE.getValue()).toString().substring(8,10) + "/" + ((java.util.Date)field_CO_DATE.getValue()).toString().substring(5,7) + "/" + ((java.util.Date)field_CO_DATE.getValue()).toString().substring(0,4));
                break;
            }
            case 1154 : // textField_3
            {
                value = (java.lang.String)("Adresse de livraison : " + ((java.lang.String)field_ST_NOM.getValue()) + " - " + ((java.lang.String)field_ST_ADRESSE.getValue()) + " - " + ((java.lang.String)field_ST_CP.getValue()) + " " + ((java.lang.String)field_ST_VILLE.getValue()));
                break;
            }
            case 1151 : // group_Fournisseur
            {
                value = (java.lang.Object)(((java.lang.String)field_FO_NOM.getValue()));
                break;
            }
            case 1155 : // variable_Fournisseur_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1161 : // textField_5
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CC_QT.getValue()).divide(new BigDecimal(1),2,java.math.BigDecimal.ROUND_HALF_EVEN));
                break;
            }
            case 1148 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1145 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1142 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1156 : // variableInitialValue_Fournisseur_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1150 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1147 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1157 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
