/*
 * Generated by JasperReports - 03/03/05 18:10
 */
import com.develog.utils.report.engine.*;
import com.develog.utils.report.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class entree extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_ST_ID = null;
    private JRFillParameter parameter_datePetit = null;
    private JRFillParameter parameter_dateGrand = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;

    private JRFillField field_AR_ID = null;
    private JRFillField field_CE_QT = null;
    private JRFillField field_ENT_ID = null;
    private JRFillField field_AR_PRIX = null;
    private JRFillField field_AR_UNIT = null;
    private JRFillField field_AR_DESIGN = null;
    private JRFillField field_ENT_DATE = null;
    private JRFillField field_TVA_TX = null;
    private JRFillField field_AR_CODE = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_prix = null;
    private JRFillVariable variable_COUT_UNITAIRE_TTC = null;
    private JRFillVariable variable_QTArticle = null;
    private JRFillVariable variable_prixTotal = null;
    private JRFillVariable variable_date = null;
    private JRFillVariable variable_totalHT = null;
    private JRFillVariable variable_totalTVA = null;
    private JRFillVariable variable_totalTTC = null;
    private JRFillVariable variable_Categorie_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_ST_ID = (JRFillParameter)parsm.get("ST_ID");
        parameter_datePetit = (JRFillParameter)parsm.get("datePetit");
        parameter_dateGrand = (JRFillParameter)parsm.get("dateGrand");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");

        field_AR_ID = (JRFillField)fldsm.get("AR_ID");
        field_CE_QT = (JRFillField)fldsm.get("CE_QT");
        field_ENT_ID = (JRFillField)fldsm.get("ENT_ID");
        field_AR_PRIX = (JRFillField)fldsm.get("AR_PRIX");
        field_AR_UNIT = (JRFillField)fldsm.get("AR_UNIT");
        field_AR_DESIGN = (JRFillField)fldsm.get("AR_DESIGN");
        field_ENT_DATE = (JRFillField)fldsm.get("ENT_DATE");
        field_TVA_TX = (JRFillField)fldsm.get("TVA_TX");
        field_AR_CODE = (JRFillField)fldsm.get("AR_CODE");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_prix = (JRFillVariable)varsm.get("prix");
        variable_COUT_UNITAIRE_TTC = (JRFillVariable)varsm.get("COUT_UNITAIRE_TTC");
        variable_QTArticle = (JRFillVariable)varsm.get("QTArticle");
        variable_prixTotal = (JRFillVariable)varsm.get("prixTotal");
        variable_date = (JRFillVariable)varsm.get("date");
        variable_totalHT = (JRFillVariable)varsm.get("totalHT");
        variable_totalTVA = (JRFillVariable)varsm.get("totalTVA");
        variable_totalTTC = (JRFillVariable)varsm.get("totalTTC");
        variable_Categorie_COUNT = (JRFillVariable)varsm.get("Categorie_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 6982 : // variable_totalHT
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_prix.getValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6969 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6994 : // textField_4
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CE_QT.getValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6997 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_AR_UNIT.getValue()));
                break;
            }
            case 6995 : // textField_5
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_prix.getValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 6999 : // textField_9
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalHT.getValue()) + " ¤");
                break;
            }
            case 6971 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6967 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7002 : // subreportParameter_ENT_ID_2
            {
                value = (java.lang.Object)(((java.lang.Integer)field_ENT_ID.getValue()));
                break;
            }
            case 6974 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6989 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
            case 6988 : // variableInitialValue_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6978 : // variable_prix
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_AR_PRIX.getValue()).floatValue()));
                break;
            }
            case 6991 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 6993 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_AR_CODE.getValue()));
                break;
            }
            case 7001 : // textField_11
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalTTC.getValue()) + " ¤");
                break;
            }
            case 7004 : // subreport_2
            {
                value = (java.lang.String)("reports/tvaReport.jasper");
                break;
            }
            case 6983 : // variable_totalTVA
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_prix.getValue()).multiply(new BigDecimal(((java.lang.Double)field_TVA_TX.getValue()).floatValue() / 100)).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6977 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6981 : // variable_prixTotal
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_AR_PRIX.getValue()).floatValue()));
                break;
            }
            case 6998 : // textField_8
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 6992 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getValue()));
                break;
            }
            case 7003 : // connection_2
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 6979 : // variable_COUT_UNITAIRE_TTC
            {
                value = (java.math.BigDecimal)((new BigDecimal(((java.lang.Double)field_AR_PRIX.getValue()).floatValue())).divide(new java.math.BigDecimal(((java.lang.Double)field_CE_QT.getValue()).floatValue()), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 7000 : // textField_10
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalTVA.getValue()) + " ¤");
                break;
            }
            case 6968 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6986 : // textField_1
            {
                value = (java.lang.String)("Entrée N°" + ((java.lang.Integer)field_ENT_ID.getValue()) + " du " + ((java.util.Date)field_ENT_DATE.getValue()).toString().substring(8,10) + "/" + ((java.util.Date)field_ENT_DATE.getValue()).toString().substring(5,7) + "/" + ((java.util.Date)field_ENT_DATE.getValue()).toString().substring(0,4));
                break;
            }
            case 6984 : // variable_totalTTC
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totalHT.getValue()).add(((java.math.BigDecimal)variable_totalTVA.getValue())));
                break;
            }
            case 6970 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6976 : // parameterDefaultValue_datePetit
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 6996 : // textField_6
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_COUT_UNITAIRE_TTC.getValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 6980 : // variable_QTArticle
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CE_QT.getValue()).floatValue()));
                break;
            }
            case 6985 : // group_Categorie
            {
                value = (java.lang.Object)(((java.lang.Integer)field_ENT_ID.getValue()));
                break;
            }
            case 6990 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 6975 : // parameterDefaultValue_dateGrand
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 6973 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6972 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6987 : // variable_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 6982 : // variable_totalHT
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_prix.getOldValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6969 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6994 : // textField_4
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CE_QT.getOldValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6997 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_AR_UNIT.getOldValue()));
                break;
            }
            case 6995 : // textField_5
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_prix.getOldValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 6999 : // textField_9
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalHT.getOldValue()) + " ¤");
                break;
            }
            case 6971 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6967 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7002 : // subreportParameter_ENT_ID_2
            {
                value = (java.lang.Object)(((java.lang.Integer)field_ENT_ID.getOldValue()));
                break;
            }
            case 6974 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6989 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
            case 6988 : // variableInitialValue_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6978 : // variable_prix
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_AR_PRIX.getOldValue()).floatValue()));
                break;
            }
            case 6991 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 6993 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_AR_CODE.getOldValue()));
                break;
            }
            case 7001 : // textField_11
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalTTC.getOldValue()) + " ¤");
                break;
            }
            case 7004 : // subreport_2
            {
                value = (java.lang.String)("reports/tvaReport.jasper");
                break;
            }
            case 6983 : // variable_totalTVA
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_prix.getOldValue()).multiply(new BigDecimal(((java.lang.Double)field_TVA_TX.getOldValue()).floatValue() / 100)).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6977 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6981 : // variable_prixTotal
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_AR_PRIX.getOldValue()).floatValue()));
                break;
            }
            case 6998 : // textField_8
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 6992 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getOldValue()));
                break;
            }
            case 7003 : // connection_2
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 6979 : // variable_COUT_UNITAIRE_TTC
            {
                value = (java.math.BigDecimal)((new BigDecimal(((java.lang.Double)field_AR_PRIX.getOldValue()).floatValue())).divide(new java.math.BigDecimal(((java.lang.Double)field_CE_QT.getOldValue()).floatValue()), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 7000 : // textField_10
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalTVA.getOldValue()) + " ¤");
                break;
            }
            case 6968 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6986 : // textField_1
            {
                value = (java.lang.String)("Entrée N°" + ((java.lang.Integer)field_ENT_ID.getOldValue()) + " du " + ((java.util.Date)field_ENT_DATE.getOldValue()).toString().substring(8,10) + "/" + ((java.util.Date)field_ENT_DATE.getOldValue()).toString().substring(5,7) + "/" + ((java.util.Date)field_ENT_DATE.getOldValue()).toString().substring(0,4));
                break;
            }
            case 6984 : // variable_totalTTC
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totalHT.getOldValue()).add(((java.math.BigDecimal)variable_totalTVA.getOldValue())));
                break;
            }
            case 6970 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6976 : // parameterDefaultValue_datePetit
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 6996 : // textField_6
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_COUT_UNITAIRE_TTC.getOldValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 6980 : // variable_QTArticle
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CE_QT.getOldValue()).floatValue()));
                break;
            }
            case 6985 : // group_Categorie
            {
                value = (java.lang.Object)(((java.lang.Integer)field_ENT_ID.getOldValue()));
                break;
            }
            case 6990 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 6975 : // parameterDefaultValue_dateGrand
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 6973 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6972 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6987 : // variable_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 6982 : // variable_totalHT
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_prix.getEstimatedValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6969 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6994 : // textField_4
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CE_QT.getValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6997 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_AR_UNIT.getValue()));
                break;
            }
            case 6995 : // textField_5
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_prix.getEstimatedValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 6999 : // textField_9
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalHT.getEstimatedValue()) + " ¤");
                break;
            }
            case 6971 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6967 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7002 : // subreportParameter_ENT_ID_2
            {
                value = (java.lang.Object)(((java.lang.Integer)field_ENT_ID.getValue()));
                break;
            }
            case 6974 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6989 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
            case 6988 : // variableInitialValue_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6978 : // variable_prix
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_AR_PRIX.getValue()).floatValue()));
                break;
            }
            case 6991 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 6993 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_AR_CODE.getValue()));
                break;
            }
            case 7001 : // textField_11
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalTTC.getEstimatedValue()) + " ¤");
                break;
            }
            case 7004 : // subreport_2
            {
                value = (java.lang.String)("reports/tvaReport.jasper");
                break;
            }
            case 6983 : // variable_totalTVA
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_prix.getEstimatedValue()).multiply(new BigDecimal(((java.lang.Double)field_TVA_TX.getValue()).floatValue() / 100)).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 6977 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6981 : // variable_prixTotal
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_AR_PRIX.getValue()).floatValue()));
                break;
            }
            case 6998 : // textField_8
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 6992 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getValue()));
                break;
            }
            case 7003 : // connection_2
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 6979 : // variable_COUT_UNITAIRE_TTC
            {
                value = (java.math.BigDecimal)((new BigDecimal(((java.lang.Double)field_AR_PRIX.getValue()).floatValue())).divide(new java.math.BigDecimal(((java.lang.Double)field_CE_QT.getValue()).floatValue()), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 7000 : // textField_10
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_totalTVA.getEstimatedValue()) + " ¤");
                break;
            }
            case 6968 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6986 : // textField_1
            {
                value = (java.lang.String)("Entrée N°" + ((java.lang.Integer)field_ENT_ID.getValue()) + " du " + ((java.util.Date)field_ENT_DATE.getValue()).toString().substring(8,10) + "/" + ((java.util.Date)field_ENT_DATE.getValue()).toString().substring(5,7) + "/" + ((java.util.Date)field_ENT_DATE.getValue()).toString().substring(0,4));
                break;
            }
            case 6984 : // variable_totalTTC
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totalHT.getEstimatedValue()).add(((java.math.BigDecimal)variable_totalTVA.getEstimatedValue())));
                break;
            }
            case 6970 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6976 : // parameterDefaultValue_datePetit
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 6996 : // textField_6
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_COUT_UNITAIRE_TTC.getEstimatedValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 6980 : // variable_QTArticle
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CE_QT.getValue()).floatValue()));
                break;
            }
            case 6985 : // group_Categorie
            {
                value = (java.lang.Object)(((java.lang.Integer)field_ENT_ID.getValue()));
                break;
            }
            case 6990 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 6975 : // parameterDefaultValue_dateGrand
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 6973 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 6972 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6987 : // variable_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
