/*
 * Generated by JasperReports - 03/06/05 17:01
 */
import com.develog.utils.report.engine.*;
import com.develog.utils.report.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class inventaire extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_ST_ID = null;
    private JRFillParameter parameter_ST_NOM = null;
    private JRFillParameter parameter_CA_REQ = null;
    private JRFillParameter parameter_CA_NOM = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;

    private JRFillField field_CS_QT = null;
    private JRFillField field_AR_ID = null;
    private JRFillField field_CA_NOM = null;
    private JRFillField field_CS_PRIXUNITAIRE = null;
    private JRFillField field_AR_UNIT = null;
    private JRFillField field_AR_DESIGN = null;
    private JRFillField field_TVA_TX = null;
    private JRFillField field_AR_CODE = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_prix = null;
    private JRFillVariable variable_COUT_UNITAIRE_TTC = null;
    private JRFillVariable variable_QTArticle = null;
    private JRFillVariable variable_prixTotal = null;
    private JRFillVariable variable_date = null;
    private JRFillVariable variable_CA_REQ = null;
    private JRFillVariable variable_Categorie_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_ST_ID = (JRFillParameter)parsm.get("ST_ID");
        parameter_ST_NOM = (JRFillParameter)parsm.get("ST_NOM");
        parameter_CA_REQ = (JRFillParameter)parsm.get("CA_REQ");
        parameter_CA_NOM = (JRFillParameter)parsm.get("CA_NOM");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");

        field_CS_QT = (JRFillField)fldsm.get("CS_QT");
        field_AR_ID = (JRFillField)fldsm.get("AR_ID");
        field_CA_NOM = (JRFillField)fldsm.get("CA_NOM");
        field_CS_PRIXUNITAIRE = (JRFillField)fldsm.get("CS_PRIXUNITAIRE");
        field_AR_UNIT = (JRFillField)fldsm.get("AR_UNIT");
        field_AR_DESIGN = (JRFillField)fldsm.get("AR_DESIGN");
        field_TVA_TX = (JRFillField)fldsm.get("TVA_TX");
        field_AR_CODE = (JRFillField)fldsm.get("AR_CODE");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_prix = (JRFillVariable)varsm.get("prix");
        variable_COUT_UNITAIRE_TTC = (JRFillVariable)varsm.get("COUT_UNITAIRE_TTC");
        variable_QTArticle = (JRFillVariable)varsm.get("QTArticle");
        variable_prixTotal = (JRFillVariable)varsm.get("prixTotal");
        variable_date = (JRFillVariable)varsm.get("date");
        variable_CA_REQ = (JRFillVariable)varsm.get("CA_REQ");
        variable_Categorie_COUNT = (JRFillVariable)varsm.get("Categorie_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1096 : // textField_5
            {
                value = (java.lang.String)("INVENTAIRE " + ((java.lang.String)parameter_CA_NOM.getValue()));
                break;
            }
            case 1098 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1078 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1083 : // parameterDefaultValue_CA_NOM
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1080 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1101 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getValue()));
                break;
            }
            case 1085 : // variable_COUT_UNITAIRE_TTC
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CS_PRIXUNITAIRE.getValue()).floatValue() * (1+(((java.lang.Double)field_TVA_TX.getValue()).floatValue() / 100))).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1090 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CA_NOM.getValue()));
                break;
            }
            case 1097 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
            case 1081 : // parameterDefaultValue_ST_NOM
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1100 : // textField_6
            {
                value = (java.lang.String)("Edition du " + DateFormat.getDateInstance().format(new Date()));
                break;
            }
            case 1073 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1103 : // textField_9
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CS_QT.getValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1104 : // textField_10
            {
                value = (java.lang.String)(new BigDecimal(((java.math.BigDecimal)variable_prix.getValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1087 : // variable_prixTotal
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CS_PRIXUNITAIRE.getValue()).floatValue() * ((java.lang.Double)field_CS_QT.getValue()).floatValue() * (1+(((java.lang.Double)field_TVA_TX.getValue()).floatValue() / 100))));
                break;
            }
            case 1075 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1102 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_AR_CODE.getValue()));
                break;
            }
            case 1077 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1089 : // group_Categorie
            {
                value = (java.lang.Object)(((java.lang.String)field_CA_NOM.getValue()));
                break;
            }
            case 1086 : // variable_QTArticle
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CS_QT.getValue()).floatValue()));
                break;
            }
            case 1093 : // variable_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1079 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1094 : // variableInitialValue_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1095 : // textField_4
            {
                value = (java.lang.String)("Edition du " + DateFormat.getDateInstance().format(new Date()));
                break;
            }
            case 1099 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 1084 : // variable_prix
            {
                value = (java.math.BigDecimal)(new BigDecimal(((((java.lang.Double)field_CS_QT.getValue()).floatValue() * ((java.lang.Double)field_CS_PRIXUNITAIRE.getValue()).floatValue()) * ((((java.lang.Double)field_TVA_TX.getValue()).floatValue() / 100)+1))));
                break;
            }
            case 1106 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)field_AR_UNIT.getValue()));
                break;
            }
            case 1091 : // textField_2
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Float)variable_QTArticle.getValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1105 : // textField_11
            {
                value = (java.lang.String)(new BigDecimal(((java.math.BigDecimal)variable_COUT_UNITAIRE_TTC.getValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1076 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1088 : // variable_CA_REQ
            {
                value = (java.lang.String)(((java.lang.String)parameter_CA_REQ.getValue()));
                break;
            }
            case 1107 : // textField_13
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 1082 : // parameterDefaultValue_CA_REQ
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1072 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1092 : // textField_3
            {
                value = (java.lang.String)(new BigDecimal(((java.lang.Float)variable_prixTotal.getValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1074 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1096 : // textField_5
            {
                value = (java.lang.String)("INVENTAIRE " + ((java.lang.String)parameter_CA_NOM.getValue()));
                break;
            }
            case 1098 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1078 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1083 : // parameterDefaultValue_CA_NOM
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1080 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1101 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getOldValue()));
                break;
            }
            case 1085 : // variable_COUT_UNITAIRE_TTC
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CS_PRIXUNITAIRE.getOldValue()).floatValue() * (1+(((java.lang.Double)field_TVA_TX.getOldValue()).floatValue() / 100))).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1090 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CA_NOM.getOldValue()));
                break;
            }
            case 1097 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
            case 1081 : // parameterDefaultValue_ST_NOM
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1100 : // textField_6
            {
                value = (java.lang.String)("Edition du " + DateFormat.getDateInstance().format(new Date()));
                break;
            }
            case 1073 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1103 : // textField_9
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CS_QT.getOldValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1104 : // textField_10
            {
                value = (java.lang.String)(new BigDecimal(((java.math.BigDecimal)variable_prix.getOldValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1087 : // variable_prixTotal
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CS_PRIXUNITAIRE.getOldValue()).floatValue() * ((java.lang.Double)field_CS_QT.getOldValue()).floatValue() * (1+(((java.lang.Double)field_TVA_TX.getOldValue()).floatValue() / 100))));
                break;
            }
            case 1075 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1102 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_AR_CODE.getOldValue()));
                break;
            }
            case 1077 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1089 : // group_Categorie
            {
                value = (java.lang.Object)(((java.lang.String)field_CA_NOM.getOldValue()));
                break;
            }
            case 1086 : // variable_QTArticle
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CS_QT.getOldValue()).floatValue()));
                break;
            }
            case 1093 : // variable_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1079 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1094 : // variableInitialValue_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1095 : // textField_4
            {
                value = (java.lang.String)("Edition du " + DateFormat.getDateInstance().format(new Date()));
                break;
            }
            case 1099 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 1084 : // variable_prix
            {
                value = (java.math.BigDecimal)(new BigDecimal(((((java.lang.Double)field_CS_QT.getOldValue()).floatValue() * ((java.lang.Double)field_CS_PRIXUNITAIRE.getOldValue()).floatValue()) * ((((java.lang.Double)field_TVA_TX.getOldValue()).floatValue() / 100)+1))));
                break;
            }
            case 1106 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)field_AR_UNIT.getOldValue()));
                break;
            }
            case 1091 : // textField_2
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Float)variable_QTArticle.getOldValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1105 : // textField_11
            {
                value = (java.lang.String)(new BigDecimal(((java.math.BigDecimal)variable_COUT_UNITAIRE_TTC.getOldValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1076 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1088 : // variable_CA_REQ
            {
                value = (java.lang.String)(((java.lang.String)parameter_CA_REQ.getValue()));
                break;
            }
            case 1107 : // textField_13
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 1082 : // parameterDefaultValue_CA_REQ
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1072 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1092 : // textField_3
            {
                value = (java.lang.String)(new BigDecimal(((java.lang.Float)variable_prixTotal.getOldValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1074 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1096 : // textField_5
            {
                value = (java.lang.String)("INVENTAIRE " + ((java.lang.String)parameter_CA_NOM.getValue()));
                break;
            }
            case 1098 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1078 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1083 : // parameterDefaultValue_CA_NOM
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1080 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1101 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_AR_DESIGN.getValue()));
                break;
            }
            case 1085 : // variable_COUT_UNITAIRE_TTC
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CS_PRIXUNITAIRE.getValue()).floatValue() * (1+(((java.lang.Double)field_TVA_TX.getValue()).floatValue() / 100))).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1090 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CA_NOM.getValue()));
                break;
            }
            case 1097 : // subreportParameter_ST_ID_1
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ST_ID.getValue()));
                break;
            }
            case 1081 : // parameterDefaultValue_ST_NOM
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1100 : // textField_6
            {
                value = (java.lang.String)("Edition du " + DateFormat.getDateInstance().format(new Date()));
                break;
            }
            case 1073 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1103 : // textField_9
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Double)field_CS_QT.getValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1104 : // textField_10
            {
                value = (java.lang.String)(new BigDecimal(((java.math.BigDecimal)variable_prix.getEstimatedValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1087 : // variable_prixTotal
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CS_PRIXUNITAIRE.getValue()).floatValue() * ((java.lang.Double)field_CS_QT.getValue()).floatValue() * (1+(((java.lang.Double)field_TVA_TX.getValue()).floatValue() / 100))));
                break;
            }
            case 1075 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1102 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_AR_CODE.getValue()));
                break;
            }
            case 1077 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1089 : // group_Categorie
            {
                value = (java.lang.Object)(((java.lang.String)field_CA_NOM.getValue()));
                break;
            }
            case 1086 : // variable_QTArticle
            {
                value = (java.lang.Float)(new Float(((java.lang.Double)field_CS_QT.getValue()).floatValue()));
                break;
            }
            case 1093 : // variable_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1079 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1094 : // variableInitialValue_Categorie_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1095 : // textField_4
            {
                value = (java.lang.String)("Edition du " + DateFormat.getDateInstance().format(new Date()));
                break;
            }
            case 1099 : // subreport_1
            {
                value = (java.lang.String)("reports/nomstock.jasper");
                break;
            }
            case 1084 : // variable_prix
            {
                value = (java.math.BigDecimal)(new BigDecimal(((((java.lang.Double)field_CS_QT.getValue()).floatValue() * ((java.lang.Double)field_CS_PRIXUNITAIRE.getValue()).floatValue()) * ((((java.lang.Double)field_TVA_TX.getValue()).floatValue() / 100)+1))));
                break;
            }
            case 1106 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)field_AR_UNIT.getValue()));
                break;
            }
            case 1091 : // textField_2
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.lang.Float)variable_QTArticle.getEstimatedValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP));
                break;
            }
            case 1105 : // textField_11
            {
                value = (java.lang.String)(new BigDecimal(((java.math.BigDecimal)variable_COUT_UNITAIRE_TTC.getEstimatedValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1076 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1088 : // variable_CA_REQ
            {
                value = (java.lang.String)(((java.lang.String)parameter_CA_REQ.getValue()));
                break;
            }
            case 1107 : // textField_13
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 1082 : // parameterDefaultValue_CA_REQ
            {
                value = (java.lang.String)(new String());
                break;
            }
            case 1072 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1092 : // textField_3
            {
                value = (java.lang.String)(new BigDecimal(((java.lang.Float)variable_prixTotal.getEstimatedValue()).floatValue()).divide(new java.math.BigDecimal(1), 2, java.math.BigDecimal.ROUND_HALF_UP) + " ¤");
                break;
            }
            case 1074 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
