/*
 * Generated by JasperReports - 03/03/05 18:11
 */
import com.develog.utils.report.engine.*;
import com.develog.utils.report.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class nomstock extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_ST_ID = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;

    private JRFillField field_ST_NOM = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_adresse = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_ST_ID = (JRFillParameter)parsm.get("ST_ID");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");

        field_ST_NOM = (JRFillField)fldsm.get("ST_NOM");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_adresse = (JRFillVariable)varsm.get("adresse");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 7024 : // subreport_5
            {
                value = (java.lang.String)("reports/telCentre.jasper");
                break;
            }
            case 7017 : // connection_2
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7008 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7007 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7023 : // connection_5
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7010 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7012 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7016 : // subreport_1
            {
                value = (java.lang.String)("reports/nomCentre.jasper");
                break;
            }
            case 7021 : // connection_4
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7020 : // subreport_3
            {
                value = (java.lang.String)("reports/cpCentre.jasper");
                break;
            }
            case 7013 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7009 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7026 : // subreport_6
            {
                value = (java.lang.String)("reports/faxCentre.jasper");
                break;
            }
            case 7022 : // subreport_4
            {
                value = (java.lang.String)("reports/villeCentre.jasper");
                break;
            }
            case 7006 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7015 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7027 : // connection_7
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7018 : // subreport_2
            {
                value = (java.lang.String)("reports/adresseCentre.jasper");
                break;
            }
            case 7019 : // connection_3
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7028 : // subreport_7
            {
                value = (java.lang.String)("reports/mailCentre.jasper");
                break;
            }
            case 7005 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7025 : // connection_6
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7014 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_ST_NOM.getValue()));
                break;
            }
            case 7011 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 7024 : // subreport_5
            {
                value = (java.lang.String)("reports/telCentre.jasper");
                break;
            }
            case 7017 : // connection_2
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7008 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7007 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7023 : // connection_5
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7010 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7012 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7016 : // subreport_1
            {
                value = (java.lang.String)("reports/nomCentre.jasper");
                break;
            }
            case 7021 : // connection_4
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7020 : // subreport_3
            {
                value = (java.lang.String)("reports/cpCentre.jasper");
                break;
            }
            case 7013 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7009 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7026 : // subreport_6
            {
                value = (java.lang.String)("reports/faxCentre.jasper");
                break;
            }
            case 7022 : // subreport_4
            {
                value = (java.lang.String)("reports/villeCentre.jasper");
                break;
            }
            case 7006 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7015 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7027 : // connection_7
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7018 : // subreport_2
            {
                value = (java.lang.String)("reports/adresseCentre.jasper");
                break;
            }
            case 7019 : // connection_3
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7028 : // subreport_7
            {
                value = (java.lang.String)("reports/mailCentre.jasper");
                break;
            }
            case 7005 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7025 : // connection_6
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7014 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_ST_NOM.getOldValue()));
                break;
            }
            case 7011 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 7024 : // subreport_5
            {
                value = (java.lang.String)("reports/telCentre.jasper");
                break;
            }
            case 7017 : // connection_2
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7008 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7007 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7023 : // connection_5
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7010 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7012 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7016 : // subreport_1
            {
                value = (java.lang.String)("reports/nomCentre.jasper");
                break;
            }
            case 7021 : // connection_4
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7020 : // subreport_3
            {
                value = (java.lang.String)("reports/cpCentre.jasper");
                break;
            }
            case 7013 : // parameterDefaultValue_ST_ID
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 7009 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7026 : // subreport_6
            {
                value = (java.lang.String)("reports/faxCentre.jasper");
                break;
            }
            case 7022 : // subreport_4
            {
                value = (java.lang.String)("reports/villeCentre.jasper");
                break;
            }
            case 7006 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7015 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7027 : // connection_7
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7018 : // subreport_2
            {
                value = (java.lang.String)("reports/adresseCentre.jasper");
                break;
            }
            case 7019 : // connection_3
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7028 : // subreport_7
            {
                value = (java.lang.String)("reports/mailCentre.jasper");
                break;
            }
            case 7005 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7025 : // connection_6
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 7014 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_ST_NOM.getValue()));
                break;
            }
            case 7011 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
